In [12]:
%%capture
import numpy as np
import matplotlib
from matplotlib import pyplot as plt
from scipy import integrate
from scipy import interpolate
import math
import sys
from scipy import signal
import pandas as pd
import tensorflow as tf
from numba import cuda
import numba
import os
from sklearn.preprocessing import MinMaxScaler
from sklearn.utils import shuffle
from IPython.display import display, HTML
%run KalmanFilter.ipynb
import mpld3
mpld3.enable_notebook()


In [2]:
# from tf.keras.models import Sequential  # This does not work!
from tensorflow.python.keras.models import Sequential
from tensorflow.python.keras.layers import Input, Dense, GRU, Embedding
from tensorflow.python.keras.optimizers import RMSprop
from tensorflow.python.keras.callbacks import EarlyStopping, ModelCheckpoint, TensorBoard, ReduceLROnPlateau
from tensorflow.python.keras import backend as K 
from IPython.display import clear_output
from tensorflow.python.keras.initializers import RandomUniform
# tf.enable_eager_execution()

In [176]:
x_dim = 11
y_dim = 2
def create_input_and_output(data, just_acc=False):
    ## Needed Data
    gps = data.gps[:,1:3] 
    acc = data.acc_ERC[:, 1:4]
    mag = data.mag[:, 1:3]
    gyro = data.gyro[:, 1:4]

    time_series = data.acc_ERC[:, 0]
    ground_truth = data.ground_truth.dis[:, 1:3]
    delta_time = np.diff(time_series, axis=0)
    delta_time = np.concatenate(([[0]], delta_time))

    # Choose which data to include in input
    if (just_acc):
        input_data = np.concatenate((gps, acc, delta_time), axis=1)
    else:
        input_data = np.concatenate((gps, acc, gyro, mag, delta_time), axis=1) ## Feature Vector Length = 11
    return input_data, ground_truth


In [177]:
def load_train_test_data(filename, train_percentage=0.8):
    #Load Data File
    data = Data_Stream(filename, load_truth=True)
    
    #Create input and ouput data
    input_data, ground_truth = create_input_and_output(data)
    
    x_dim = input_data.shape[1]
    y_dim = ground_truth.shape[1]

    num_train = int(train_percentage*len(input_data))
    num_test = len(input_data) - num_train

    training_data   = input_data[:num_train, :]
    training_labels = ground_truth[:num_train, :]

    test_data     = input_data[num_train:, :]
    test_labels   = ground_truth[num_train:, :]
    
    return training_data, training_labels, test_data, test_labels, data.gps

In [178]:
gps_bound = 3000.0
acc_bound = 3000.0 #Actual bound (30)
gyro_bound = 3000.0 #Actual bound (2)
mag_bound = 3000.0 #Actual bound (30)
dt_bound = 3000.0 #Actual bound (0.1)

custom_scale_matrix = np.asmatrix([gps_bound, gps_bound,
                                   acc_bound, acc_bound, acc_bound, 
                                   gyro_bound, gyro_bound, gyro_bound,
                                   mag_bound, mag_bound, dt_bound])
custom_scale_matrix = np.concatenate((custom_scale_matrix, -custom_scale_matrix))

print(custom_scale_matrix)
x_scaler = MinMaxScaler()
x_scaler = x_scaler.fit(custom_scale_matrix)
y_scaler = MinMaxScaler()
y_scaler = y_scaler.fit(custom_scale_matrix[:, 0:2])

def scale_data(training_data, training_labels, test_data, test_labels):

    norm_training_data = x_scaler.transform(training_data)
    norm_test_data = x_scaler.transform(test_data)
    norm_training_labels = y_scaler.transform(training_labels)
    norm_test_labels = y_scaler.transform(test_labels)
    
    
    return norm_training_data, norm_training_labels, norm_test_data, norm_test_labels
    

[[ 3000.  3000.  3000.  3000.  3000.  3000.  3000.  3000.  3000.  3000.
   3000.]
 [-3000. -3000. -3000. -3000. -3000. -3000. -3000. -3000. -3000. -3000.
  -3000.]]


In [191]:
def batch_generator(batch_size, sequence_length):
    

    x_seqs = []
    y_seqs = []
    
    ##Create all sequences
    for i in range(0, len(norm_training_data) - sequence_length, 1):
        x_seqs.append(norm_training_data[i:i+sequence_length])
        y_seqs.append(norm_training_labels[i:i+sequence_length])
    x_seqs = np.asarray(x_seqs)
    y_seqs = np.asarray(y_seqs)
    
    print(x_seqs.shape)
    
    x_seqs, y_seqs = shuffle(x_seqs, y_seqs)
    #Print number of batches required to pass all sequences in an epoch
    print("Batches per Epoch: ", int(len(x_seqs)/batch_size + 1))
    while True:
        
        #For each batch in an epoch, given n sequences that are in shuffled order
        for i in range(int(len(x_seqs)/batch_size + 1)):
            i1 = i+1
            yield (x_seqs[i*batch_size:i1*batch_size], y_seqs[i*batch_size:i1*batch_size])
        #Shuffle sequences between epochs
        x_seqs, y_seqs = shuffle(x_seqs, y_seqs)
        

In [180]:
training_data, training_labels, test_data, test_labels,_ = load_train_test_data('uni.csv', 0.8)

norm_training_data, norm_training_labels, norm_test_data, norm_test_labels = scale_data(training_data, training_labels, 
                                                                                        test_data, test_labels)



Parsed File
Freq. of Acceleration 1583.554443181799
Freq. of Lin. Acceleration 669.8833983859098
Freq. of Gyroscope 1585.3892195648934
Interpolated Samples
Loaded Ground Truth
Rotated Acceleration
Integrated Acceleration


In [194]:
generator = batch_generator(batch_size=512, sequence_length=100)


In [195]:

batches = []
batches.append(next(generator))
print(batches[-1][0])
for i in range(159):
    batches.append(next(generator))
print(batches[-1][0].shape)


(81292, 100, 11)
Batches per Epoch:  159
[[[0.42468934 0.50880333 0.49972448 ... 0.50595104 0.49670768 0.50000126]
  [0.42468617 0.5088037  0.49975084 ... 0.50586017 0.49673633 0.50000084]
  [0.42468301 0.50880407 0.49977411 ... 0.50586104 0.49670724 0.50000084]
  ...
  [0.42430896 0.50884808 0.50004287 ... 0.506232   0.49753317 0.50000084]
  [0.4243058  0.50884845 0.50006471 ... 0.50623179 0.49756201 0.50000084]
  [0.42430263 0.50884882 0.50008957 ... 0.50623158 0.49759091 0.50000084]]

 [[0.48725649 0.50055255 0.50015923 ... 0.50487082 0.49613044 0.50000042]
  [0.48725244 0.50055185 0.50016075 ... 0.50478018 0.49621682 0.50000126]
  [0.48724975 0.50055138 0.50015479 ... 0.50471983 0.49627433 0.50000084]
  ...
  [0.48696254 0.50050187 0.50026988 ... 0.50487628 0.49646592 0.50000042]
  [0.48695984 0.5005014  0.50026748 ... 0.50493583 0.4964374  0.50000084]
  [0.4869517  0.5005     0.50025152 ... 0.5047513  0.49626426 0.50000252]]

 [[0.37427893 0.51481007 0.49995291 ... 0.50457216 0.50

In [47]:
def custom_loss(y_true, y_pred):
    
    y_true_slice = y_true[:, warmup_steps:, :]
    y_pred_slice = y_pred[:, warmup_steps:, :]
    
    
#     ts = tf.reshape(y_true_slice, (-1, 2))
    
#     ps = tf.reshape(y_pred_slice, (-1, 2))
    
#     def get_min_dist(pi):
# #         print(pi.get_shape(), ts.get_shape())
#         eu_dists = tf.norm(ts-pi, ord='euclidean', axis=1)
#         min_dist = tf.reduce_min(eu_dists)
#         return min_dist


#     min_dists = tf.map_fn(get_min_dist, ps, dtype=tf.float32)
#     print("Minimum distances to Ground Truth Points Shape", min_dists.get_shape())
#     mean_dist = tf.reduce_mean(min_dists)
#     print("Mean Mimimum Distance Shape", mean_dist.get_shape())
    
# #     min_dists_tot = 0.0
# #     print(ps.shape)
# #     for pi in ps:
# #         min_t = sys.float_info.max
# #         for ti in ts:
# #             t = tf.norm(ti-pi, ord='euclidean')
# #             if(t < min_t):
# #                 min_t = t
# #         min_dists_tot += min_t
        
# #     mean_dist = min_dists_tot/len(ps)
    
    eu_dists = tf.norm(y_true_slice-y_pred_slice, ord='euclidean')
    loss_mean = tf.reduce_mean(eu_dists)
    
    return loss_mean

In [8]:
class PlotLosses(tf.keras.callbacks.Callback):
    def on_train_begin(self, logs={}):
        self.i = 0
        self.x = []
        self.losses = []
        self.val_losses = []
        
        self.fig = plt.figure(figsize=(20, 10))
        
        self.logs = []

    def on_epoch_end(self, epoch, logs={}):
        
        self.logs.append(logs)
        self.x.append(self.i)
        self.losses.append(logs.get('loss'))
        self.val_losses.append(logs.get('val_loss'))
        self.i += 1
        
        clear_output(wait=True)
        plt.figure(figsize=(10, 8))
        plt.plot(self.x, self.losses, label="loss")
        plt.plot(self.x, self.val_losses, label="val_loss")
        plt.legend()
        plt.ioff()
        plt.show();

In [198]:
def plot_comparison(filename, start_index=0, individual_signals=False, train_percentage=0.8, seq_len=100):
    training_data, training_labels, test_data, test_labels, orig_gps = load_train_test_data(filename, train_percentage)

    
    trial_input = np.concatenate((training_data, test_data))
    ground_truth = np.concatenate((training_labels, test_labels))
    
    #Pad input
    padding = np.zeros((seq_len, training_data.shape[1]))
    trial_input = np.concatenate((padding,trial_input))

    ##Scale down the trial input, get predicted output
    trial_input = x_scaler.transform(trial_input)
    trial_input = np.expand_dims(trial_input, axis=0)
    predicted_output = model.predict(trial_input)
    
    
    ## Remove data upto the start point
    ground_truth = ground_truth[start_index:]
    orig_gps = orig_gps[start_index:]
    predicted_output = y_scaler.inverse_transform(predicted_output[0])[start_index+seq_len:]
    

    # The output of the model is between 0 and 1. Inverse rescale to get input
    if(individual_signals):
        for signal in range(ground_truth_output.shape[1]):

            # Make the plotting-canvas bigger.
            plt.figure(figsize=(8,5))

            # Plot and compare the ground truth and Model predicted versions
            plt.plot(ground_truth[:, signal],'ro', label='true')
            plt.plot(predicted_output[:, signal], label='pred')

            # Plot grey box for warmup-period.
            p = plt.axvspan(0, warmup_steps, facecolor='red', alpha=0.15)

            # Plot labels etc.
            plt.ylabel("X Displacement" if signal == 0 else "Y Displacement")
            plt.xlabel("Timestep")
            plt.legend()
            plt.show()
            
    ##Print Graphs of X against Y
    plt.figure(figsize=(8,5))
    plt.plot(ground_truth[:, 0], ground_truth[:, 1], label='ground truth', color = 'g')
    plt.plot(predicted_output[:len(training_data), 0], predicted_output[:len(training_data), 1], 
             label='seen training data', color = 'b')
    plt.plot(predicted_output[len(training_data):, 0], predicted_output[len(training_data):, 1], 
             label='unseen test data', color = 'c')
    plt.plot(orig_gps[:, 1], orig_gps[:, 2], label='original gps', color = 'r')
    plt.legend()
    plt.show()
    
    print("Accuracy of GPS: ", measure_accuracy(ground_truth, orig_gps[:, 1:3]))
    print("Accuracy of RNN: ", measure_accuracy(ground_truth, predicted_output))
        

### Print Data with Pandas

In [10]:
# if(print_outputs):

#     if(False):
#         training_frame = pd.DataFrame(np.concatenate((training_data, training_labels), axis=1), 
#                                                      columns=['GPS X', 'GPS Y', 'Acc X', 'Acc Y', 
#                                                               'Delta Time', 'Ground Truth X', 'Ground_Truth Y'])
#     else:
#         training_frame = pd.DataFrame(np.concatenate((training_data, training_labels), axis=1), 
#                                                      columns=['GPS X', 'GPS Y', 'Acc X', 'Acc Y',
#     #                                                           'Vel X', 'Vel Y',
#     #                                                           'Mag X', 'Mag Y',
#     #                                                           'Gyro X', 'Gyro Y', 'Gyro Z',
#                                                               'Delta Time', 'Ground Truth X', 'Ground_Truth Y'])
#     print("Training Data")
#     display(training_frame.head(5))
#     training_frame.plot(figsize=(20,10))

In [11]:
# if(print_outputs):

#     if(False):
#         test_frame = pd.DataFrame(np.concatenate((test_data, test_labels), axis=1), 
#                                                      columns=['GPS X', 'GPS Y', 'Acc X', 'Acc Y', 
#                                                               'Delta Time', 'Ground Truth X', 'Ground_Truth Y'])
#     else:
#         test_frame = pd.DataFrame(np.concatenate((test_data, test_labels), axis=1), 
#                                                      columns=['GPS X', 'GPS Y', 'Acc X', 'Acc Y',
#     #                                                           'Vel X', 'Vel Y',
#     #                                                           'Mag X', 'Mag Y',
#     #                                                           'Gyro X', 'Gyro Y', 'Gyro Z',
#                                                               'Delta Time', 'Ground Truth X', 'Ground_Truth Y'])
#     print("Testing Data")
#     display(test_frame.head(5))
#     # test_frame.plot(figsize=(20,10))
